import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/components/shared/header";
import {Footer} from "@/components/shared/footer";
import React from "react";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin", "cyrillic"], // выбираешь нужные подмножества
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
    <body>

    <Header/>
    <main>{children}</main>
    <Footer/>

    </body>
    </html>
  );
}
